***
*** ReFox X  #UK933629  MANRIQUE ORELLANA  MANSOFT SYSTEMS [VFP50]
***



ON ERROR DO HANDLE_ERR WITH LINENO(),SYS(16)
PUBLIC ODBC_MANAGER,pub_database,LCIMG_PATH,PUB_IP,PUB_M_NO,OBJ1,PUB_USER_PHOTO,PUB_IMG,PUB_ATTCHMENT,PUB_DATABACK,PUB_LOGO,PUB_BACK,PUB_CAPTION,PUB_BKIMG
PUB_DATABASE='SQL SERVER'

*!*	_SCREEN.hide
*!*	_SCREEN.icon = "picture\tct.ico"
_SCREEN.CAPTION = "捷安特厂商管理系统"
*!*	_SCREEN.picture = "picture\sky.bmp"

SET SYSMENU OFF  &&不显示VFP系统菜单
SET TALK OFF  &&关闭程序运算的显示过程
SET SAFETY OFF &&关闭改写已有文件之前显示的确认对话框
SET DELETED ON &&不显示被逻辑删除的记录
SET CENTURY ON&&让日期在显示或输入时的年份为四位数
SET DATE TO ymd&&让日期在显示或输入时的顺序为年月日
*!*	set mark to ‘-’&&让日期之间的间隔符为“-”
SET STATUS BAR OFF&&不显示VFP的状态条
*!*	modify windows screen title ’永立MES系统’ noclose &&应用程序的标题显示内容为“人事管理系统” 。不如_screen.caption=’人事管理系统’更简洁

_SCREEN.CONTROLBOX=.T. &&不显示狐狸头和主窗口右上角的三个按钮

*!*	_screen.WindowState=2
_SCREEN.HEIGHT=746
_SCREEN.WIDTH=1198
DO ODBC
ODBC_MANAGER=SQLCONNECT("CHANGSHANG","wewit","wewit")

SET SYSMENU TO _MEDIT
_SCREEN.AUTOCENTER = .T.
_SCREEN.ICON = "E:\天帆\厂商进出软件\项目源码\PICTURE\tainfan.ico"

_SCREEN.CLOSABLE = .F.
_SCREEN.MAXBUTTON=.F.
_SCREEN.ADDOBJECT('lab_Demo',  ;
	'Label')
_SCREEN.lab_demo.CAPTION = '演示数据：2004年06月'
_SCREEN.lab_demo.AUTOSIZE = .T.
_SCREEN.lab_demo.TOP = 38
_SCREEN.lab_demo.LEFT = 204
_SCREEN.lab_demo.BACKSTYLE = 0
*!*	_SCREEN.windowstate = 2
_SCREEN.ADDOBJECT('img_Tree', 'Image')
_SCREEN.img_tree.HEIGHT =_SCREEN.HEIGHT
_SCREEN.img_tree.WIDTH =_SCREEN.WIDTH
_SCREEN.img_tree.BACKSTYLE = 0
_SCREEN.img_tree.PICTURE = 'picture\bkg_main.bmp'
_SCREEN.img_tree.STRETCH = 2        && 不想变形就设为 1
*!*	_Screen.img_tree.Move(0,0,_Screen.Width,_Screen.Height)


STRSQL="SELECT * FROM [supplier_manager].[dbo].[SYS_INI] WHERE SYS_NO='SYS_LOGO'"
SQLRUN(0000000017,SYS(16),STRSQL,"SYS_logo")
PUB_LOGO=ALLTRIM(SYS_logo.SYS_COMMENT)
IF !EMPTY(PUB_LOGO)
	_SCREEN.ICON=PUB_LOGO
ENDIF

STRSQL="SELECT * FROM [supplier_manager].[dbo].[SYS_INI] WHERE SYS_NO='SYS_CAPTION'"
SQLRUN(0000000017,SYS(16),STRSQL,"SYS_CAPTION")
PUB_CAPTION=ALLTRIM(SYS_CAPTION.SYS_COMMENT)

STRSQL="SELECT * FROM [supplier_manager].[dbo].[SYS_INI] WHERE SYS_NO='BACKGROUND'"
SQLRUN(0000000017,SYS(16),STRSQL,"SYS_BACKGROUND")
PUB_BKIMG=ALLTRIM(SYS_BACKGROUND.SYS_COMMENT)
IF !EMPTY(PUB_LOGO)
	_SCREEN.ICON=PUB_LOGO
ELSE
	_SCREEN.ICON='/PICTURE/TAINFAN.ICO'
ENDIF
IF !EMPTY(PUB_CAPTION)
	_SCREEN.CAPTION=PUB_CAPTION
ELSE
	_SCREEN.CAPTION='捷安特厂管理系统'
ENDIF
IF !EMPTY(PUB_BKIMG)
	_SCREEN.Picture=PUB_BKIMG
ELSE
	_SCREEN.Picture='/PICTURE/BACK.PNG'
ENDIF
*!*	STRSQL="select substring(sys.fn_sqlvarbasetostr(HashBytes('MD5','F')),3,32) AS JIAMI2"
*!*	SQLRUN(0000000073,SYS(16),STRSQL,'MD5_REGISTER2')
*!*	STRSQL="SELECT * FROM [supplier_manager].[dbo].[SYS_INI] WHERE SYS_NO='register_key' AND SYS_COMMENT='"+ALLTRIM(MD5_REGISTER2.JIAMI2)+"'"
*!*	SQLRUN(0000000072,SYS(16),STRSQL,'SEL_INI_REGISTER')
*!*	SELECT SEL_INI_REGISTER
*!*	IF RECCOUNT()>0
*!*		DO FORM ZHUCEJI NAME OBJ3
*!*		OBJ3.CAPTION=ALLTRIM(_SCREEN.CAPTION)+"注册程序"
*!*		OBJ3.ICON=_SCREEN.Icon
*!*		_SCREEN.Picture='/PICTURE/BACK.PNG'
*!*	ELSE
*!*		DO FORM LOGIN_MAIN NAME OBJ1
*!*	ENDIF


STORE 0 TO getval,c_qf
c_cd=256
ls_volumnename=SPACE(256)
ls_filename=SPACE(256)
DECLARE INTEGER GetVolumeInformation IN Win32API STRING @,STRING @,INTEGER, LONG @,;
	INTEGER @,INTEGER @,STRING @,INTEGER
=GetVolumeInformation("C:\",@ls_volumnename,256,@getval,@c_cd,@c_qf,@ls_filename,256)
IF getval<0
	getval=INT(getval+2^32)
ENDIF
CLEAR DLLS
hdsnumber=ALLT(STR(getval))
LCCOM_NO=LEFT(ALLTRIM(SYS(0)),AT("#",ALLTRIM(SYS(0)))-2)
STRSQL="SELECT * FROM [supplier_manager].[dbo].[REGISTER] WHERE PC_NO='"+ALLTRIM(LCCOM_NO)+"' AND JIQIHAOMA='"+ALLTRIM(hdsnumber)+"'"
SQLRUN(0000000077,SYS(16),STRSQL,'SEL_JIHUO2')
SELECT SEL_JIHUO2
IF RECCOUNT()=0
	DO FORM ZHUCEJI NAME OBJ3
	OBJ3.CAPTION=ALLTRIM(_SCREEN.CAPTION)+"注册程序"
	OBJ3.ICON=_SCREEN.ICON
	_SCREEN.PICTURE='/PICTURE/BACK.PNG'
ELSE
	STRSQL="select substring(sys.fn_sqlvarbasetostr(HashBytes('MD5','F')),3,32) AS JIAMI2"
	SQLRUN(0000000073,SYS(16),STRSQL,'MD5_REGISTER2')
	IF EMPTY(ALLTRIM(SEL_JIHUO2.JIHUOMA)) AND ALLTRIM(SEL_JIHUO2.JIHUO_STATUS)=ALLTRIM(MD5_REGISTER2.JIAMI2)
		DO FORM ZHUCEJI NAME OBJ3
		OBJ3.CAPTION=ALLTRIM(_SCREEN.CAPTION)+"注册程序"
		OBJ3.ICON=_SCREEN.ICON
		_SCREEN.PICTURE='/PICTURE/BACK.PNG'
	ELSE
		DO FORM LOGIN_MAIN NAME OBJ1
		OBJ1.CAPTION=_SCREEN.Caption
		OBJ1.ICON=_SCREEN.ICON
		OBJ1.PICTURE=_SCREEN.Picture
		OBJ1.REFRESH
		_SCREEN.Hide
	ENDIF
ENDIF
READ EVENTS  &&开始事件处理

RETURN &&暂停往下执行
