* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
*  文件名: FTREFRESHFROMIO.PRG <-- 本文件由 UnFoxAll 创建
* -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-


 FFS_MP = OBJ_FORM4.MOUSEPOINTER
 OBJ_FORM4.MOUSEPOINTER = 11
  SQLSETPROP(0,'DispLogin',3)
 IF EMPTY(MDB)
 ODBC_ANT2000IO = SQLCONNECT('ant2000IO','ant','tct1810')
 ELSE 
 ODBC_ANT2000IO = SQLCONNECT(MDB,'ant','tct1810')
 ENDIF 
 IF ODBC_ANT2000IO < 0
  SQLSETPROP(0,'DispLogin',1)
 IF EMPTY(MDB)
 ODBC_ANT2000IO = SQLCONNECT('ant2000IO','ant','tct1810')
 ELSE 
 ODBC_ANT2000IO = SQLCONNECT(MDB,'ant','tct1810')
 ENDIF 
 ENDIF 
 IF ODBC_ANT2000IO < 0
 IF PUB_LANGUAGE
 = MESSAGEBOX('Database Connecting Error!',64,'Ant2000 System')
 ELSE 
 = MESSAGEBOX('接后台识别系统数据库连接错误！',64,'就餐管理系统')
 ENDIF 
 OBJ_FORM4.MOUSEPOINTER = FFS_MP
 RETURN 
 ENDIF 
 SJDATE1 = GETANTENV('KQGD','SJDATE1')
 SJDATE2 = GETANTENV('KQGD','SJDATE2')
 SJDAYS = GETANTENV('KQGD','SJDAYS')
 DO GETKQQJ
 STRSQL =  ;
      "select rybh,lyxm,cardno,company,djrq,yxks,yxjs from sb_card_ls where hsbz=0 and yxjs>'" +  ;
DTOC(PUB_KQKAISHI) + "'"
 IF SQLEXEC(ODBC_ANT2000IO,STRSQL,'card_ls') <> 1
 = MESSAGEBOX('打开识别系统临时卡号表错误！',64,'ANT2000人事考勤系统')
 = SQLDISCONNECT(ODBC_ANT2000IO)
 OBJ_FORM4.MOUSEPOINTER = FFS_MP
 RETURN 
 ENDIF 
 = SQLDISCONNECT(ODBC_ANT2000IO)
 UPDATE card_ls SET YXJS = '9999/12/31' WHERE CTOD(YXJS) = CTOD('')
 SELECT COUN( * )  LSCOUNT WHERE BMBH LIKE 'LS-%' INTO CURSOR lsbm FROM bm
 IF LSCOUNT = 0
 SELECT LEFT(COMPANY,20)  COMPANY INTO CURSOR tmpbm DISTINCT FROM card_ls
 BMCOUNT = 0
 SCAN 
 BMCOUNT = BMCOUNT + 1
 INSERT INTO bm ( BMBH , BMMC ) VALUES ( 'LS-' + ALLTRIM(STR(BMCOUNT)) , TMPBM.COMPANY )
 ENDSCAN 
 ENDIF 
 STRSQL =  ;
      'select a.zgbh,a.zgxm,a.bmbh,a.lzsj,a.dh,a.zglb,b.lskh,b.djsj,b.yxks,b.yxjs,16777215 as ModifyFlag' +  ;
' from kq_zg a right join kq_lskh b on a.zgbh=b.zgbh where a.zgbh is not null order by a.zgbh'
  SQLEXE_RUN(65,SYS(16),STRSQL,'ZGLINK')
 UPDATE zglink SET YXJS = DTOC(CTOD(LZSJ) - 1) WHERE CTOD(LZSJ) <> CTOD('')
 UPDATE zglink SET YXJS = '9999/12/31' WHERE CTOD(YXJS) = CTOD('')
 UPDATE zglink SET YXKS = DTOC(DATE()) WHERE CTOD(YXKS) = CTOD('')
 UPDATE zglink SET ZGLB = '1' WHERE  .NOT. ZGBH LIKE '5%'
 UPDATE zglink SET ZGLB = '2' WHERE ZGBH LIKE '5%'
 SELECT ZGBH , COUN(LSKH) GROUP BY ZGBH HAVING COUN(LSKH) > 1 INTO CURSOR multicard FROM  ;
      zglink
 SELECT MULTICARD
 SCAN 
 SELECT LSKH WHERE ZGBH == MULTICARD.ZGBH ORDER BY YXJS DESCENDING INTO CURSOR tmpcard  ;
      FROM zglink
 ISFIRST = .T.
 SELECT TMPCARD
 SCAN 
 IF ISFIRST
 ISFIRST = .F.
 LOOP 
 ENDIF 
 DELETE FROM zglink WHERE LSKH == TMPCARD.LSKH
 ENDSCAN 
 ENDSCAN 
 SELECT BM
 INDEX ON BMMC TAG BM
 SELECT CARD_LS
 SCAN 
 IF LEFT(CARD_LS.RYBH,1) = '2'
 LOOP 
 ENDIF 
 SELECT BM
 IF SEEK(LEFT(CARD_LS.COMPANY,20))
 INSERT INTO zglink ( ZGBH , ZGXM , BMBH , LZSJ , DH , ZGLB , LSKH , DJSJ , YXKS , YXJS ,  ;
      MODIFYFLAG ) VALUES ( 'LS-' + RIGHT(ALLTRIM(CARD_LS.RYBH),7) ,  ;
      CARD_LS.LYXM , BM.BMBH , '9999/12/31' , 0 ,  ;
      IIF(LEFT(CARD_LS.RYBH,1) = '9','4','3') , CARD_LS.CARDNO , CARD_LS.DJRQ , CARD_LS.YXKS , CARD_LS.YXJS ,  ;
      16777215 )
 ENDIF 
 ENDSCAN 
 DELETE FROM zglink WHERE  ;
      YXJS < "'" + DTOC(PUB_KQKAISHI) + "'" AND  .NOT. EMPTY(CTOD(YXJS))
 SELECT ZGLINK
 INDEX ON ZGBH TO zglink
 COPY TO temp STRUCTURE 
 USE IN 0 temp ALIAS TEMP
 SELECT ZGLINK
 SET RELATION TO ZGBH INTO ZG
 SCAN 
 IF EOF('ZG') AND (CTOD(ZGLINK.LZSJ) = CTOD('') .OR. CTOD(ZGLINK.LZSJ) >= PUB_KQKAISHI)
 SELECT TEMP
 APPEND BLANK
 REPLACE ZGBH WITH ZGLINK.ZGBH , MODIFYFLAG WITH RGB(180,213,252)
 PUB_MODIFYFLAG = .T.
 REPLACE ZGXM WITH ZGLINK.ZGXM
 REPLACE BMBH WITH ZGLINK.BMBH
 REPLACE DH WITH 0
 REPLACE ZGLB WITH ZGLINK.ZGLB
 SELECT ZGLINK
 ENDIF 
 ENDSCAN 
 SET RELATION TO
 SELECT ZG
 SET RELATION TO ZGBH INTO ZGLINK
 SCAN 
 IF LEFT(ZGBH,4) = 'LS-2'
 REPLACE MODIFYFLAG WITH RGB(0,0,0)
 PUB_MODIFYFLAG = .T.
 DELETE 
 ENDIF 
 IF EOF('ZGLINK')
 LOOP 
 ENDIF 
 IF CTOD(ZGLINK.LZSJ) <> CTOD('') AND CTOD(ZGLINK.LZSJ) < PUB_KQKAISHI
 REPLACE MODIFYFLAG WITH RGB(0,0,0)
 PUB_MODIFYFLAG = .T.
 DELETE 
 ELSE 
 IF ZG.ZGXM <> ZGLINK.ZGXM
 REPLACE ZGXM WITH ZGLINK.ZGXM
 IF MODIFYFLAG <> RGB(180,213,252)
 REPLACE MODIFYFLAG WITH RGB(255,193,193)
 PUB_MODIFYFLAG = .T.
 ENDIF 
 ENDIF 
 IF ZG.BMBH <> ZGLINK.BMBH
 IF LEFT(ZG.ZGBH,3) <> 'LS-' AND LEFT(ZG.ZGBH,1) <> '3'
 REPLACE BMBH WITH ZGLINK.BMBH
 IF MODIFYFLAG <> RGB(180,213,252)
 REPLACE MODIFYFLAG WITH RGB(255,193,193)
 PUB_MODIFYFLAG = .T.
 ENDIF 
 ENDIF 
 ENDIF 
 IF ZG.ZGLB <> ZGLINK.ZGLB
 REPLACE ZGLB WITH ZGLINK.ZGLB
 IF MODIFYFLAG <> RGB(180,213,252)
 REPLACE MODIFYFLAG WITH RGB(255,193,193)
 PUB_MODIFYFLAG = .T.
 ENDIF 
 ENDIF 
 ENDIF 
 ENDSCAN 
 SET RELATION TO
 SELECT TEMP
 USE 
 SELECT BM
 INDEX ON BMBH TO bm
 SELECT ZG
 APPEND FROM temp
 SET RELATION TO BMBH INTO BM
 SET RELATION ADDITIVE TO ZGLB INTO YGLB
 GO TOP
 OBJ_FORM4.MOUSEPOINTER = FFS_MP
 = MESSAGEBOX('就餐员工资料刷新完成。',64,'就餐管理系统')
*
