PARAMETER PARA_TAG, PARA_SRC
TAG_FDS = FCOUNT("&para_tag")
SRC_FDS = FCOUNT("&para_src")
MREPLACE = ""
FOR I = 1 TO TAG_FDS
MFD = FIELD(I,"&para_tag")
FOR J = 1 TO SRC_FDS
IF MFD==FIELD(J,"&para_src")
IF  .NOT. EMPTY(MREPLACE)
MREPLACE = MREPLACE+","+MFD+" with "+PARA_SRC+"."+MFD
ELSE
MREPLACE = "replace "+MFD+" with "+PARA_SRC+"."+MFD
ENDIF
EXIT
ENDIF
ENDFOR
ENDFOR
IF  .NOT. EMPTY(MREPLACE)
SELECT &PARA_SRC
SCAN
SELECT &PARA_TAG
APPEND BLANK
&MREPLACE
SELECT &PARA_SRC
ENDSCAN
ENDIF
ENDPROC
**
