PARAMETER PARA_TAG, PARA_SRC, PARA_LEFT
TAG_FDS = FCOUNT("&para_tag")
SRC_FDS = FCOUNT("&para_src")
MREPLACE = ""
FOR I = 1 TO TAG_FDS
MFD = LEFT(FIELD(I,"&para_tag"),PARA_LEFT)
FOR J = 1 TO SRC_FDS
MFD_TAG = PARA_TAG+"."+FIELD(I,"&para_tag")			
MFD_SRC = PARA_SRC+"."+FIELD(J,"&para_src")
IF MFD==LEFT(FIELD(J,"&para_src"),PARA_LEFT) AND TYPE("&mfd_tag")=TYPE("&mfd_src")
IF  .NOT. EMPTY(MREPLACE)
MREPLACE = MREPLACE+","+FIELD(I,"&para_tag")+" with "+PARA_SRC+"."+FIELD(J,"&para_src")
ELSE
MREPLACE = "replace "+FIELD(I,"&para_tag")+" with "+PARA_SRC+"."+FIELD(J,"&para_src")
ENDIF
EXIT
ENDIF
ENDFOR
ENDFOR
IF  .NOT. EMPTY(MREPLACE)
SELECT &PARA_SRC
SCAN
SELECT &PARA_TAG
APPEND BLANK
&MREPLACE
SELECT &PARA_SRC
ENDSCAN
ENDIF
ENDPROC
**
