**
FUNCTION AutoCount
PARAMETER AUTOCOUNT_XUHAO
AUTOCOUNT_AREA = STR(SELECT())
AUTOCOUNT_RET = -1
AUTOCOUNT_CNT = 0
DO WHILE AUTOCOUNT_RET=-1 .AND. AUTOCOUNT_CNT<10
SQLEXE_RUN(00000000018, SYS(16), "select * from sys_counter where xuhao=?AutoCount_XuHao", "counter")
IF EOF()
= MESSAGEBOX("ID Counter Error!", 64, "Ant2000 System")
EXIT
ELSE
IF 1=SQLEXE_RUN(00000000023, SYS(16), "update sys_counter set jishuqi=?jishuqi+1 where xuhao=?AutoCount_XuHao", "")
AUTOCOUNT_RET = JISHUQI+1
ELSE
AUTOCOUNT_CNT = AUTOCOUNT_CNT+1
ENDIF
ENDIF
ENDDO
SELECT &AUTOCOUNT_AREA
RETURN AUTOCOUNT_RET
ENDFUNC
**
