**
FUNCTION CheckWithdrawalDepositRefund
PARAMETER PLSLODGINGGUID
CURRENT_AREA = STR(SELECT())
N_RET = 0
STRSQL = "SELECT "
STRSQL = STRSQL+"w.DepositRefund,"
STRSQL = STRSQL+"w.LodgingGuid"
STRSQL = STRSQL+" from Withdrawal w"
STRSQL = STRSQL+" WHERE w.LodgingGuid=?plsLodgingGuid"
STRSQL = STRSQL+" ORDER BY w.AddTime"
SQLEXE_RUN(00000000025, SYS(16), STRSQL, "ltSettleMonthly2WithdrawalChk")
SELECT LTSETTLEMONTHLY2WITHDRAWALCHK
GOTO TOP
IF  .NOT. EOF()
IF DEPOSITREFUND=.T.
N_RET = 1
ENDIF
ENDIF
USE
SELECT &CURRENT_AREA
RETURN N_RET
ENDFUNC
**
