**
FUNCTION ChkDup2
PARAMETER CHKDUP_CONDS
GETHL_CURR_AREA = LTRIM(STR(SELECT()))
SELECT KQ_ATT2ANTEMP
CHKDUP_RET = .F.
IF  .NOT. EOF()
CHKDUP_REC = RECNO()
ELSE
CHKDUP_REC = 0
ENDIF
LOCATE FOR &CHKDUP_CONDS
IF FOUND()
CHKDUP_RET = .T.
ELSE
ENDIF
IF CHKDUP_REC>0
GOTO CHKDUP_REC
ENDIF
SELECT &GETHL_CURR_AREA			
RETURN CHKDUP_RET
ENDFUNC
**
