**
FUNCTION ChkIn
LPARAMETERS CHKIN_P1, CHKIN_P2, CHKIN_P3
CHKIN_RET = .F.
IF CHKIN_P1<>0 .AND. CHKIN_P2<>0 .AND. CHKIN_P3<>0
IF CHKIN_P3>=CHKIN_P2
IF CHKIN_P1>=CHKIN_P2 .AND. CHKIN_P1<=CHKIN_P3
CHKIN_RET = .T.
ENDIF
ELSE
IF (CHKIN_P1>=CHKIN_P2 .AND. CHKIN_P1<=1440) .OR. (CHKIN_P1>0 .AND. CHKIN_P1<=CHKIN_P3)
CHKIN_RET = .T.
ENDIF
ENDIF
ENDIF
RETURN CHKIN_RET
ENDFUNC
**
