PUBLIC PUB_VER
IF PUB_BANBEN="ÑÝÊ¾°æ"
PUB_VER = "1111"
RETURN
ENDIF
MVER = GETANTENV("SETUP", "SUBSYS")
IF  .NOT. EMPTY(MVER)
MVER = SYSPASS(MVER, .F.)
MSET = LEFT(MVER, 2)+SUBSTR(MVER, 5, 1)+SUBSTR(MVER, 8, 2)
PUB_VER = SUBSTR(MVER, 3, 2)+SUBSTR(MVER, 6, 2)
DO CASE
CASE MSET=="setup"
MVER = "SE"+LEFT(PUB_VER, 2)+"T"+RIGHT(PUB_VER, 2)+"UP"
MVER = SYSPASS(MVER, .T.)
SETANTENV("SETUP", "SUBSYS", MVER)
CASE MSET=="SETUP"
OTHERWISE
PUB_VER = "    "
ENDCASE
ELSE
PUB_VER = "    "
ENDIF
ENDPROC
**
