**
FUNCTION ChkYMDisSettled
LPARAMETERS SYMD
LSCHKYMDISSETTLED_CURRAREA = LTRIM(STR(SELECT()))
MRET = .F.
STRSQL = "SELECT "
STRSQL = STRSQL+"s.Company,"
STRSQL = STRSQL+"s.Year AS 年份,"
STRSQL = STRSQL+"s.Month AS 月份,"
STRSQL = STRSQL+"s.StartDate,"
STRSQL = STRSQL+"'1234/12/12' AS sKSRQ,"
STRSQL = STRSQL+"s.EndDate,"
STRSQL = STRSQL+"'1234/12/12' AS sJSRQ,"
STRSQL = STRSQL+"s.Locked,"
STRSQL = STRSQL+"y.Name AS 是否锁定,"
STRSQL = STRSQL+"s.LockTime,"
STRSQL = STRSQL+"s.SettleGuid"
STRSQL = STRSQL+" from "
STRSQL = STRSQL+" Settle s "
STRSQL = STRSQL+" LEFT OUTER JOIN SysCdYesNo y ON s.Locked=y.Code"
STRSQL = STRSQL+" WHERE s.Company=?gsCompany"
STRSQL = STRSQL+" ORDER BY s.Year,s.Month "
SQLEXE_RUN(00000000040, SYS(16), STRSQL, "ltSettleMonthlyQry1")
SELECT LTSETTLEMONTHLYQRY1
REPLACE SKSRQ WITH DTOC(STARTDATE), SJSRQ WITH DTOC(ENDDATE) ALL
GOTO BOTTOM
IF  .NOT. EOF()
LSJSRQ = SJSRQ
IF CTOD(SYMD)<=CTOD(LSJSRQ)
MRET = .T.
ENDIF
ENDIF
USE
SELECT &LSCHKYMDISSETTLED_CURRAREA
RETURN MRET
ENDFUNC
**
