**
FUNCTION GetAntEnv
PARAMETER SECTION, VARIABLE
SRET = ""
SSECTION = ALLTRIM(UPPER(SECTION))
SVARIABLE = ALLTRIM(UPPER(VARIABLE))
MAREA = LTRIM(STR(SELECT()))
IF SQLEXE_RUN(00000000014, SYS(16), "select * from sys_ini where SEC=?ssection and VAR=?sVariable", "sys")=1
SELECT SYS
IF  .NOT. EOF()
DO CASE
CASE TYP='N'
SRET = VAL(SYS.VAL)
CASE TYP='D'
SRET = CTOD(SYS.VAL)
OTHERWISE
SRET = TRIM(SYS.VAL)
ENDCASE
ENDIF
USE
ELSE
= MESSAGEBOX("GetAntEnv函数Error！", 64, "考勤分析系统")
ENDIF
SELECT &MAREA					
RETURN SRET
ENDFUNC
**
