**
FUNCTION GetCount
PARAMETER GETCOUNT_XUHAO
GETCOUNT_AREA = STR(SELECT())
DO WHILE .T.
GETCOUNT_I = SQLEXE_RUN(00000000011, SYS(16), "select * from sys_counter where xuhao=?GetCount_XuHao", "counter")
IF GETCOUNT_I>0
IF EOF()
GETCOUNT_RET = -1
ELSE
IF FLAG=' '
GETCOUNT_RET = JISHUQI
= SQLEXE_RUN(00000000018, SYS(16), "update sys_counter set flag='1' where xuhao=?GetCount_XuHao", "")
ELSE
GETCOUNT_J = MESSAGEBOX("其他用户正在保存该数据表。", 0321, "考勤分析系统")
DO CASE
CASE GETCOUNT_J=4
LOOP
CASE GETCOUNT_J=5
GETCOUNT_RET = JISHUQI
= SQLEXE_RUN(00000000026, SYS(16), "update sys_counter set flag='1' where xuhao=?GetCount_XuHao", "")
OTHERWISE
GETCOUNT_RET = -1
ENDCASE
ENDIF
ENDIF
ELSE
GETCOUNT_RET = -1
ENDIF
EXIT
ENDDO
SELECT &GETCOUNT_AREA
RETURN GETCOUNT_RET
ENDFUNC
**
