**
FUNCTION GetCompanyOptionValue
PARAMETER GCOVCOMPANY, OPTIONID, VALTYPE
MAREA = LTRIM(STR(SELECT()))
IF SQLEXE_RUN(00000000013, SYS(16), "select * from CompanyOptions where Company=?gcovCompany AND OptionId=?OptionId", "GetCompanyOptionValue")=1
SELECT GETCOMPANYOPTIONVALUE
IF  .NOT. EOF()
DO CASE
CASE UPPER(VALTYPE)=UPPER('Boolean')
SRET = BOOLEANVALUE
CASE UPPER(VALTYPE)=UPPER('Int')
SRET = INTVALUE
CASE UPPER(VALTYPE)=UPPER('DateTime')
SRET = DATETIMEVALUE
CASE UPPER(VALTYPE)=UPPER('String')
SRET = ALLTRIM(STRINGVALUE)
WAIT WINDOW SRET
CASE UPPER(VALTYPE)=UPPER('Text')
SRET = TEXTVALUE
CASE UPPER(VALTYPE)=UPPER('Float')
SRET = FLOATVALUE
CASE UPPER(VALTYPE)=UPPER('Guid')
SRET = GUIDVALUE
CASE UPPER(VALTYPE)=UPPER('Money')
SRET = MONEYVALUE
OTHERWISE
SRET = ""
ENDCASE
ELSE
SRET = ""
ENDIF
USE
ELSE
= MESSAGEBOX("GetCompanyOptionº¯ÊýError_1£¡", 64, "CompanyOption")
ENDIF
SELECT &MAREA					
RETURN SRET
ENDFUNC
**
