YY = YEAR(DATE())
MM = MONTH(DATE())
DD = SJDATE2
MDATE = CTOD(STR(YY, 4)+'.'+STR(MM, 2)+'.'+STR(DD, 2))
I = 1
DO WHILE CTOD("")=MDATE .AND. I<5
DD = DD-1
MDATE = CTOD(STR(YY, 4)+'.'+STR(MM, 2)+'.'+STR(DD, 2))
I = I+1
ENDDO
IF I>=5
MDATE = CTOD("")
ENDIF
PUB_KQJIESHU = MDATE
DD = SJDATE1
IF ABS(SJDATE2-SJDATE1)>=30
MDATE = CTOD(STR(YY, 4)+'.'+STR(MM, 2)+'.'+STR(DD, 2))
ELSE
IF MM=1
MDATE = CTOD(STR(YY-1, 4)+'.'+STR(12, 2)+'.'+STR(DD, 2))
ELSE
MDATE = CTOD(STR(YY, 4)+'.'+STR(MM-1, 2)+'.'+STR(DD, 2))
ENDIF
ENDIF
I = 1
DO WHILE CTOD("")=MDATE .AND. I<5
DD = DD-1
MDATE = CTOD(STR(YY, 4)+'.'+STR(MM, 2)+'.'+STR(DD, 2))
I = I+1
ENDDO
IF I>=5
MDATE = CTOD("")
ENDIF
PUB_KQKAISHI = MDATE
ENDPROC
**
