**
FUNCTION GetLanguage
PARAMETER VARIABLE
SET EXACT ON
SRET = ""
SVARIABLE = ALLTRIM(UPPER(VARIABLE))
IF LANGUAGEFILEPOINTER>0
FSEEK(LANGUAGEFILEPOINTER, 0, 0)
DO WHILE  .NOT. FEOF(LANGUAGEFILEPOINTER)
SBUF = LTRIM(FGETS(LANGUAGEFILEPOINTER))
SSTR = UPPER(SBUF)
L = AT("=", SSTR)
IF L<2 .OR. SVARIABLE<>ALLTRIM(SUBSTR(SSTR, 1, L-1))
LOOP
ENDIF
SRET = ALLTRIM(SUBSTR(SBUF, L+1, 1024))
EXIT
ENDDO
ENDIF
SET EXACT ON
RETURN SRET
ENDFUNC
**
