**
FUNCTION GETQX
PARAMETER SUBSYS, MODE
MAREA = ALLTRIM(STR(SELECT()))
MRET = "error"
DO CASE
CASE SUBSYS="RS"
DO CASE
CASE MODE="BM"
= SQLEXE_RUN(00000000024, SYS(16), "select * from  rs_qx_bm", "temp")
SELECT TEMP
SET FILTER TO NAME=PUB_USER
MRET = ""
MALL = .T.
SCAN
IF QX>0
IF EMPTY(MRET)
MRET = "(@='"+ALLTRIM(BMBH)+"'"
ELSE
MRET = MRET+" or @='"+ALLTRIM(BMBH)+"'"
ENDIF
ELSE
MALL = .F.
ENDIF
ENDSCAN
IF MALL
MRET = "1=1"
ELSE
IF EMPTY(MRET)
MRET = "1=2"
ELSE
MRET = MRET+")"
ENDIF
ENDIF
CASE MODE="GYXZ"
= SQLEXE_RUN(00000000054, SYS(16), "select * from  rs_qx_gyxz", "temp")
SELECT TEMP
SET FILTER TO NAME=PUB_USER
MRET = ""
MALL = .T.
SCAN
IF QX>0
IF EMPTY(MRET)
MRET = "(@="+ALLTRIM(STR(CODE))
ELSE
MRET = MRET+" or @="+ALLTRIM(STR(CODE))
ENDIF
ELSE
MALL = .F.
ENDIF
ENDSCAN
IF MALL
MRET = "1=1"
ELSE
IF EMPTY(MRET)
MRET = "1=2"
ELSE
MRET = MRET+")"
ENDIF
ENDIF
OTHERWISE
= SQLEXE_RUN(00000000084, SYS(16), "select * from rs_qx_hm", "temp")
SELECT TEMP
SET FILTER TO HMBH=MODE
MRET = "true"
IF  .NOT. EOF()
LOCATE FOR NAME=PUB_USER .AND. QX>0
IF EOF()
MRET = "false"
ELSE
MRET = MRET+ALLTRIM(STR(QX))
ENDIF
ELSE
MRET = "false"
ENDIF
ENDCASE
CASE SUBSYS="KQ"
DO CASE
CASE MODE="BM"
= SQLEXE_RUN(00000000105, SYS(16), "select * from  kq_qx_bm", "temp")
SELECT TEMP
SET FILTER TO NAME=PUB_USER
MRET = ""
MALL = .T.
SCAN
IF QX>0
IF EMPTY(MRET)
MRET = "(@='"+ALLTRIM(BMBH)+"'"
ELSE
MRET = MRET+" or @='"+ALLTRIM(BMBH)+"'"
ENDIF
ELSE
MALL = .F.
ENDIF
ENDSCAN
IF MALL
MRET = "1=1"
ELSE
IF EMPTY(MRET)
MRET = "1=2"
ELSE
MRET = MRET+")"
ENDIF
ENDIF
OTHERWISE
= SQLEXE_RUN((00000000134), SYS(16), "select * from kq_qx_hm", "temp")
SELECT TEMP
SET FILTER TO HMBH=MODE
MRET = "true"
IF  .NOT. EOF()
LOCATE FOR NAME=PUB_USER .AND. QX>0
IF EOF()
MRET = "false"
ELSE
MRET = MRET+ALLTRIM(STR(QX))
ENDIF
ELSE
MRET = "false"
ENDIF
ENDCASE
CASE SUBSYS="GZ"
DO CASE
CASE MODE="XZDM"
= SQLEXE_RUN((00000000155), SYS(16), "select * from  gz_qx_xzxm", "temp")
SELECT TEMP
SET FILTER TO NAME=PUB_USER
MRET = ""
MALL = .T.
SCAN
IF QX>0
IF EMPTY(MRET)
MRET = "(@="+ALLTRIM(STR(XUHAO))
ELSE
MRET = MRET+" or @="+ALLTRIM(STR(XUHAO))
ENDIF
ELSE
MALL = .F.
ENDIF
ENDSCAN
IF MALL
MRET = "1=1"
ELSE
IF EMPTY(MRET)
MRET = "1=2"
ELSE
MRET = MRET+")"
ENDIF
ENDIF
CASE MODE="BM"
= SQLEXE_RUN((00000000185), SYS(16), "select * from  gz_qx_bm", "temp")
SELECT TEMP
SET FILTER TO NAME=PUB_USER
MRET = ""
MALL = .T.
SCAN
IF QX>0
IF EMPTY(MRET)
MRET = "(@='"+ALLTRIM(BMBH)+"'"
ELSE
MRET = MRET+" or @='"+ALLTRIM(BMBH)+"'"
ENDIF
ELSE
MALL = .F.
ENDIF
ENDSCAN
IF MALL
MRET = "1=1"
ELSE
IF EMPTY(MRET)
MRET = "1=2"
ELSE
MRET = MRET+")"
ENDIF
ENDIF
CASE MODE="YGLB"
= SQLEXE_RUN((00000000215), SYS(16), "select * from  gz_qx_yglb", "temp")
SELECT TEMP
SET FILTER TO NAME=PUB_USER
MRET = ""
MALL = .T.
SCAN
IF QX>0
IF EMPTY(MRET)
MRET = "(@='"+ALLTRIM(LBBH)+"'"
ELSE
MRET = MRET+" or @='"+ALLTRIM(LBBH)+"'"
ENDIF
ELSE
MALL = .F.
ENDIF
ENDSCAN
IF MALL
MRET = "1=1"
ELSE
IF EMPTY(MRET)
MRET = "1=2"
ELSE
MRET = MRET+")"
ENDIF
ENDIF
OTHERWISE
= SQLEXE_RUN((00000000245), SYS(16), "select * from gz_qx_hm", "temp")
SELECT TEMP
SET FILTER TO HMBH=MODE
MRET = "true"
IF  .NOT. EOF()
LOCATE FOR NAME=PUB_USER .AND. QX>0
IF EOF()
MRET = "false"
ELSE
MRET = MRET+ALLTRIM(STR(QX))
ENDIF
ELSE
MRET = "false"
ENDIF
ENDCASE
CASE SUBSYS="FT"
= SQLEXE_RUN(00000000264, SYS(16), "select * from FT_qx_hm", "temp")
SELECT TEMP
SET FILTER TO HMBH=MODE
MRET = "true"
IF  .NOT. EOF()
LOCATE FOR NAME=PUB_USER .AND. QX>0
IF EOF()
MRET = "false"
ELSE
MRET = MRET+ALLTRIM(STR(QX))
ENDIF
ELSE
MRET = "false"
ENDIF
CASE SUBSYS="TL"
= SQLEXE_RUN(00000000282, SYS(16), "select * from tl_qx_hm", "temp")
SELECT TEMP
SET FILTER TO HMBH=MODE
MRET = "true"
IF  .NOT. EOF()
LOCATE FOR NAME=PUB_USER .AND. QX>0
IF EOF()
MRET = "false"
ELSE
MRET = MRET+ALLTRIM(STR(QX))
ENDIF
ELSE
MRET = "false"
ENDIF
ENDCASE
IF MRET="error"
= MESSAGEBOX("权限调用参数错误", 64, "ANT2000人事考勤系统")
MRET = "false"
ENDIF
USE
SELECT &MAREA
RETURN MRET
ENDFUNC
**
