**
FUNCTION GetRepKey
LPARAMETERS GRK_MOD
GRK_RET = ""
DO CASE
CASE GRK_MOD="KEY"
DO CASE
CASE REPLIST.ATTR1=1
GRK_RET = "RQ,ZGBH"
CASE REPLIST.ATTR1=2
GRK_RET = "RQ,BMBH"
CASE REPLIST.ATTR1=3
GRK_RET = "RQ,RIQI"
CASE REPLIST.ATTR1=4
GRK_RET = "RQ,ZGLB"
CASE REPLIST.ATTR1=5 .OR. REPLIST.ATTR1=6
GRK_RET = ALLTRIM(REPLIST.PKEY)
ENDCASE
CASE GRK_MOD="WHERE"
DO CASE
CASE REPLIST.ATTR1=1
GRK_RET = "RQ=?RQ AND ZGBH=?ZGBH"
CASE REPLIST.ATTR1=2
GRK_RET = "RQ=?RQ AND BMBH=?BMBH"
CASE REPLIST.ATTR1=3
GRK_RET = "RQ=?RQ AND RIQI=?RIQI"
CASE REPLIST.ATTR1=4
GRK_RET = "RQ=?RQ AND ZGLB=?ZGLB"
CASE REPLIST.ATTR1=5 .OR. REPLIST.ATTR1=6
MPKEY = ALLTRIM(REPLIST.PKEY)
MLEN = LEN(MPKEY)
DO WHILE MLEN>0
MPOS = AT(",", MPKEY)
MFD = LEFT(MPKEY, IIF(MPOS=0, MLEN, MPOS-1))
IF  .NOT. EMPTY(GRK_RET)
GRK_RET = GRK_RET+" AND "+MFD+"=?"+MFD
ELSE
GRK_RET = MFD+"=?"+MFD
ENDIF
MPKEY = RIGHT(MPKEY, MLEN-LEN(MFD)-1)
MLEN = LEN(MPKEY)
ENDDO
ENDCASE
ENDCASE
RETURN GRK_RET
ENDFUNC
**
