**
FUNCTION hex2dec
PARAMETER HEX_STR
DEC_INT = 0
DEC_TMP = 0
DEC_STR = ''
HEX_STR = ALLTRIM(HEX_STR)
DO WHILE LEFT(HEX_STR, 1)=='0'
HEX_STR = SUBSTR(HEX_STR, 2)
ENDDO
IF LEN(HEX_STR)>13
RETURN .NULL.
ENDIF
FOR I = LEN(HEX_STR) TO 1 STEP -1
STR_TMP = SUBSTR(HEX_STR, LEN(HEX_STR)-I+1, 1)
DO CASE
CASE STR_TMP$'ABCDEFabcdef'
DEC_TMP = ASC(UPPER(STR_TMP))-55
CASE STR_TMP$'0123456789'
DEC_TMP = VAL(STR_TMP)
OTHERWISE
RETURN .NULL.
ENDCASE
DEC_INT = DEC_INT+DEC_TMP*(16**(I-1))
ENDFOR
DEC_STR = ALLTRIM(STR(DEC_INT, 16))
RETURN DEC_STR
ENDFUNC
**
