**
PROCEDURE InsertTbSettleWaterCardReissue
PARAMETER PLSSETTLEMONTHLYNEWGUID, PLSCOMPANY, PLNWATERCARDREGCOPENCOUNT, PLNWATERCARDREGCOPENAMOUNT, PLNWATERCARDREGCINCOMECOUNT, PLNWATERCARDREGCINCOMEAMOUNT, PLNWATERCARDREGCPAYCOUNT, PLNWATERCARDREGCPAYAMOUNT, PLNWATERCARDREGCSURPLUSCOUNT, PLNWATERCARDREGCSURPLUSAMOUNT, PLNWATERCARDREGCCOUNTTOTAL, PLNWATERCARDREGCAMOUNTTOTAL
STRSQL1 = ""
STRSQL1 = STRSQL1+"INSERT INTO SettleWaterCardReissue ("
STRSQL1 = STRSQL1+"RowGuid,"
STRSQL1 = STRSQL1+"SettleGuid,"
STRSQL1 = STRSQL1+"Company,"
STRSQL1 = STRSQL1+"OpenCount	,"
STRSQL1 = STRSQL1+"OpenAmount,"
STRSQL1 = STRSQL1+"IncomeCount,"
STRSQL1 = STRSQL1+"IncomeAmount,"
STRSQL1 = STRSQL1+"PayCount,"
STRSQL1 = STRSQL1+"PayAmount,"
STRSQL1 = STRSQL1+"SurplusCount,"
STRSQL1 = STRSQL1+"SurplusAmount,"
STRSQL1 = STRSQL1+"CountTotal,"
STRSQL1 = STRSQL1+"AmountTotal"
STRSQL2 = ""
STRSQL2 = STRSQL2+") VALUES ("
STRSQL2 = STRSQL2+"NewId(),"
STRSQL2 = STRSQL2+"?plsSettleMonthlyNewGuid,"
STRSQL2 = STRSQL2+"?plsCompany,"
STRSQL2 = STRSQL2+"?plnWaterCardReGcOpenCount,"
STRSQL2 = STRSQL2+"?plnWaterCardReGcOpenAmount,"
STRSQL2 = STRSQL2+"?plnWaterCardReGcIncomeCount,"
STRSQL2 = STRSQL2+"?plnWaterCardReGcIncomeAmount,"
STRSQL2 = STRSQL2+"?plnWaterCardReGcPayCount,"
STRSQL2 = STRSQL2+"?plnWaterCardReGcPayAmount,"
STRSQL2 = STRSQL2+"?plnWaterCardReGcSurplusCount,"
STRSQL2 = STRSQL2+"?plnWaterCardReGcSurplusAmount,"
STRSQL2 = STRSQL2+"?plnWaterCardReGcCountTotal,"
STRSQL2 = STRSQL2+"?plnWaterCardReGcAmountTotal"
STRSQL2 = STRSQL2+")"
NRET = SQLEXE_RUN(00000000066, SYS(16), STRSQL1+STRSQL2, "")
IF NRET=0
= MESSAGEBOX("SettleWaterCardReissueÐÂÔöÊ§°Ü£¡"+PLSCOMPANY, 016, THISFORM.CAPTION)
RETURN
ELSE
ENDIF
ENDPROC
**
