**
PROCEDURE InsertTbSettleDepositDetail
PARAMETER PLSSETTLEMONTHLYNEWGUID, PLSCOMPANY, PLSSTAFFCOMPANY, PLSLODGINGGUID, PLNDEPOSIT, PLSDEPOSITTYPE, PLSDEPOSITTYPE1, PLSDEPOSITTYPE2, PLSDEPOSITTYPE3, PLSDEPOSITMEMO
STRSQL1 = ""
STRSQL1 = STRSQL1+"INSERT INTO SettleDepositDetail ("
STRSQL1 = STRSQL1+"RowGuid,"
STRSQL1 = STRSQL1+"SettleGuid,"
STRSQL1 = STRSQL1+"Company,"
STRSQL1 = STRSQL1+"StaffCompany,"
STRSQL1 = STRSQL1+"LodgingGuid,"
STRSQL1 = STRSQL1+"Deposit,"
STRSQL1 = STRSQL1+"Type,"
STRSQL1 = STRSQL1+"Type1,"
STRSQL1 = STRSQL1+"Type2,"
STRSQL1 = STRSQL1+"Type3,"
STRSQL1 = STRSQL1+"Memo"
STRSQL2 = ""
STRSQL2 = STRSQL2+") VALUES ("
STRSQL2 = STRSQL2+"newid(),"
STRSQL2 = STRSQL2+"?plsSettleMonthlyNewGuid,"
STRSQL2 = STRSQL2+"?plsCompany,"
STRSQL2 = STRSQL2+"?plsStaffCompany,"
STRSQL2 = STRSQL2+"?plsLodgingGuid,"
STRSQL2 = STRSQL2+"?plnDeposit,"
STRSQL2 = STRSQL2+"?plsDepositType,"
STRSQL2 = STRSQL2+"?plsDepositType1,"
STRSQL2 = STRSQL2+"?plsDepositType2,"
STRSQL2 = STRSQL2+"?plsDepositType3,"
STRSQL2 = STRSQL2+"?plsDepositMemo"
STRSQL2 = STRSQL2+")"
NRET = SQLEXE_RUN(00000000051, SYS(16), STRSQL1+STRSQL2, "")
IF NRET=0
= MESSAGEBOX("新增月结押金明细失败！", 016, THISFORM.CAPTION)
RETURN
ENDIF
ENDPROC
**
