**
PROCEDURE InsertTbSettleWaterCardReissueDetail
PARAMETER PLSISSUEGUID, PLSSETTLEMONTHLYNEWGUID, PGSCOMPANY, PLSSTAFFCOMPANY, PLSLODGINGGUID, PLNAMOUNT, PLSTYPE, PLSTYPE1, PLSTYPE2, PLSMEMO
STRSQL1 = ""
STRSQL1 = STRSQL1+"INSERT INTO SettleWaterCardReissueDetail ("
STRSQL1 = STRSQL1+"RowGuid,"
STRSQL1 = STRSQL1+"SettleGuid,"
STRSQL1 = STRSQL1+"IssueGuid,"
STRSQL1 = STRSQL1+"Company,"
STRSQL1 = STRSQL1+"StaffCompany,"
STRSQL1 = STRSQL1+"LodgingGuid,"
STRSQL1 = STRSQL1+"Amount,"
STRSQL1 = STRSQL1+"Type,"
STRSQL1 = STRSQL1+"Type1,"
STRSQL1 = STRSQL1+"Type2,"
STRSQL1 = STRSQL1+"Memo"
STRSQL2 = ""
STRSQL2 = STRSQL2+") VALUES ("
STRSQL2 = STRSQL2+"newid(),"
STRSQL2 = STRSQL2+"?plsSettleMonthlyNewGuid,"
STRSQL2 = STRSQL2+"?plsIssueGuid,"
STRSQL2 = STRSQL2+"?pgsCompany,"
STRSQL2 = STRSQL2+"?plsStaffCompany,"
STRSQL2 = STRSQL2+"?plsLodgingGuid,"
STRSQL2 = STRSQL2+"?plnAmount,"
STRSQL2 = STRSQL2+"?plsType,"
STRSQL2 = STRSQL2+"?plsType1,"
STRSQL2 = STRSQL2+"?plsType2,"
STRSQL2 = STRSQL2+"?plsMemo"
STRSQL2 = STRSQL2+")"
NRET = SQLEXE_RUN(00000000055, SYS(16), STRSQL1+STRSQL2, "")
IF NRET=0
= MESSAGEBOX("新增《补办水卡》明细失败2！", 016, "Proc_InsertTbSettleWaterCardReissueDetail")
RETURN
ENDIF
ENDPROC
**
