**
FUNCTION ReadStrFromFile
PARAMETER SFILENAME, SOUTPUTSTRING
GNFILEHANDLE = FOPEN(SFILENAME)
GNEND = FSEEK(GNFILEHANDLE, 0, 2)
GNTOP = FSEEK(GNFILEHANDLE, 0)
IF GNEND<=0
ELSE
SOUTPUTSTRING = FREAD(GNFILEHANDLE, GNEND)
ENDIF
= FCLOSE(GNFILEHANDLE)
RETURN SOUTPUTSTRING
ENDFUNC
**
