**
FUNCTION SaveStrToTxt
PARAMETER SSOURCESTRING, SFILENAME
NWRITEDNUMBER = 0
SOUTPUTFILENAME = SFILENAME
GNOUTPUTFILEHANDLE = FCREATE(SOUTPUTFILENAME, 0)
NWRITEDNUMBER = FPUTS(GNOUTPUTFILEHANDLE, SSOURCESTRING)
= FCLOSE(GNOUTPUTFILEHANDLE)
RETURN 1
ENDFUNC
**
