PARAMETER RUNSQL_LINE, RUNSQL_CXM, RUNSQL_STR, RUNSQL_TBL
IF  .NOT. EMPTY(RUNSQL_STR)
DO WHILE SQLEXEC(ODBC_ANT2000, RUNSQL_STR, RUNSQL_TBL)=-1
RUNSQL_RET = HANDLE_SQL(RUNSQL_LINE, RUNSQL_CXM)
DO CASE
CASE RUNSQL_RET=-99
IF PUB_IFREL=1
&PUB_OBJECT(PUB_LEVEL)..RELEASE
ELSE
IF PUB_IFREL=-1
PUB_IFFORMERR = 1
ENDIF
ENDIF
IF PUB_IFBACKUP=1
DO RELEBKUP
ENDIF
DO SYSEXIT
CASE RUNSQL_RET=-98
IF PUB_IFREL=0
IF PUB_IFMOVE=0
RETURN TO MASTER 
ELSE
IF PUB_LEVEL=4
&PUB_OBJECT(3)..ENABLED=.T.
&PUB_OBJECT(3)..LEFT=PUB_LEFT2
&PUB_OBJECT(3)..TOP=PUB_TOP2
&PUB_OBJECT(2)..SHOW
&PUB_OBJECT(3)..SHOW
ELSE
IF PUB_LEVEL=3
&PUB_OBJECT(2)..ENABLED=.T.
&PUB_OBJECT(2)..LEFT=PUB_LEFT1
&PUB_OBJECT(2)..TOP=PUB_TOP1
ENDIF
ENDIF
RETURN TO MASTER 
ENDIF
ELSE
IF PUB_IFREL=1
IF PUB_LEVEL<3
&PUB_OBJECT(PUB_LEVEL)..ENABLED=.T.
&PUB_OBJECT(PUB_LEVEL)..RELEASE
DO SYSEXIT
ELSE
IF PUB_IFBACKUP=1
PUB_IFBACKUP = 0
DO RELEBKUP
ENDIF
&PUB_OBJECT(PUB_LEVEL)..RELEASE
RETURN TO MASTER 
ENDIF
ELSE
PUB_IFFORMERR = 1
RETURN TO MASTER 
ENDIF
ENDIF
CASE RUNSQL_RET=0
LOOP
CASE RUNSQL_RET=-1
RETURN -1
ENDCASE
EXIT
ENDDO
RETURN 1
ENDIF
ENDFUNC
**
FUNCTION Handle_sql
PARAMETER ERRLINE, PROGRAMNAME
DIMENSION AERRORARRAY(7)
CNTROL = AERROR(AERRORARRAY)
IF CNTROL<=0
RETURN 1
ENDIF
ERRNO = AERRORARRAY(1)
ERRTEXT = AERRORARRAY(2)
ERRTEXT = ERRTEXT+CHR(13)+CHR(13)+"程序名:  "+PROGRAMNAME+CHR(13)+"错误行:  "+ALLTRIM(STR(ERRLINE))
IF ERRNO=1526
ERRNO = AERRORARRAY(5)
ERRTEXT = AERRORARRAY(3)
ERRTEXT = ERRTEXT+CHR(13)+CHR(13)+"程序名:  "+PROGRAMNAME+CHR(13)+"错误行:  "+ALLTRIM(STR(ERRLINE))
DO CASE
CASE PUB_DATABASE="ACCESS"
DO CASE
CASE ERRNO=-1053
= MESSAGEBOX(ERRTEXT, 048, "警告")
RETURN -1
CASE ERRNO=-1302
ERRTEXT = ERRTEXT+CHR(13)+CHR(13)+"是否重试?"
RESULT = MESSAGEBOX(ERRTEXT, 053, "警告")
IF RESULT=4
RETURN 0
ELSE
RETURN -98
ENDIF
CASE ERRNO=-1303
= MESSAGEBOX(ERRTEXT, 048, "警告")
RETURN -1
CASE ERRNO=-1605
RETURN -1
OTHERWISE
ERRTEXT = STR(ERRNO)+CHR(13)+ERRTEXT
MESSAGEBOX(ERRTEXT, 048, "系统错误")
RETURN -99
ENDCASE
CASE PUB_DATABASE="SQL SERVER"
DO CASE
CASE ERRNO=515
= MESSAGEBOX(ERRTEXT, 048, "警告")
RETURN -1
CASE ERRNO=2714
= MESSAGEBOX(ERRTEXT, 048, "警告")
RETURN -1
CASE ERRNO=2627
RETURN -1
OTHERWISE
ERRTEXT = STR(ERRNO)+CHR(13)+ERRTEXT
MESSAGEBOX(ERRTEXT, 048, "系统错误")
RETURN -99
ENDCASE
CASE PUB_DATABASE="INTERBASE"
DO CASE
CASE ERRNO=-625
= MESSAGEBOX(ERRTEXT, 048, "警告")
RETURN -1
CASE ERRNO=-607
= MESSAGEBOX(STR(ERRNO)+CHR(13)+ERRTEXT, 048, "警告")
RETURN -1
CASE ERRNO=-803
RETURN -1
OTHERWISE
ERRTEXT = STR(ERRNO)+CHR(13)+ERRTEXT
MESSAGEBOX(ERRTEXT, 048, "系统错误")
RETURN -99
ENDCASE
OTHERWISE
ERRTEXT = STR(ERRNO)+CHR(13)+ERRTEXT
= MESSAGEBOX(ERRTEXT, 048, "系统错误")
RETURN -99
ENDCASE
ELSE
ERRTEXT = STR(ERRNO)+CHR(13)+ERRTEXT
= MESSAGEBOX(ERRTEXT, 048, "系统错误")
RETURN -99
ENDIF
RETURN 1
ENDFUNC
**
