**
FUNCTION strDecrypt2
PARAMETER ENCRYPTIONSTRING
DECRYPT = ""
= RAND(100001)
N = 0
DO WHILE N<8
X = HEXVAL(ENCRYPTIONSTRING, 2*N+1)
= RAND(INT(RAND()*X)+1)
N = N+1
ENDDO
L = LEN(RTRIM(ENCRYPTIONSTRING))
DO WHILE N<L/2
X = HEXVAL(ENCRYPTIONSTRING, 2*N+1)
X = BITXOR(INT(RAND()*255), X)
DECRYPT = DECRYPT+CHR(X)
N = N+1
ENDDO
RETURN DECRYPT
ENDFUNC
**
FUNCTION HexVal
PARAMETER X, N
X1 = SUBSTR(X, N, 1)
X2 = SUBSTR(X, N+1, 1)
DO CASE
CASE BETWEEN(X1, '0', '9')
X1VAL = ASC(X1)-48
CASE BETWEEN(X1, 'A', 'F')
X1VAL = ASC(X1)-65+10
ENDCASE
DO CASE
CASE BETWEEN(X2, '0', '9')
X2VAL = ASC(X2)-48
CASE BETWEEN(X2, 'A', 'F')
X2VAL = ASC(X2)-65+10
ENDCASE
HEXVAL = X1VAL*16+X2VAL
RETURN HEXVAL
ENDFUNC
**
