IF ODBC_ANT2000=-1
QUIT
RETURN
ENDIF
SAVE TO client ALL LIKE Sys*
_SCREEN.SHOW
IF ODBC_ANT2000<>-1
= SQLDISCONNECT(ODBC_ANT2000)
ENDIF
ODBC_ANT2000 = -1
ERASE *.idx
ERASE *.cdx
MDBF = SYS(2000, "*.dbf")
DO WHILE  .NOT. EMPTY(MDBF)
IF MDBF<>"FOXUSER.DBF" .AND. LEFT(MDBF, 4)<>"LOC_"
ERASE &MDBF
ENDIF
MDBF = SYS(2000, "*.dbf", 1)
ENDDO
IF PUB_LANGUAGE
= CLOSELANGUAGE()
ENDIF
OBJ_ANT2000 = .NULL.
RELEASE ALL
CANCEL
RETURN
ERASE *.idx
ERASE *.cdx
MDBF = SYS(2000, "*.dbf")
DO WHILE  .NOT. EMPTY(MDBF)
IF MDBF<>"FOXUSER.DBF" .AND. LEFT(MDBF, 4)<>"LOC_"
ERASE &MDBF
ENDIF
MDBF = SYS(2000, "*.dbf", 1)
ENDDO
IF PUB_BANBEN<>"ÑÝÊ¾°æ"
RELEASE ALL
QUIT
ELSE
RELEASE ALL
CANCEL
ENDIF
ENDPROC
**
