PARAMETER SL_LOGLEVEL, SL_LOCATION, SL_DESCRIPTION
IF SL_LOGLEVEL<SYSLOGLEVEL
SL_DESCRIPTION = STRTRAN(SL_DESCRIPTION, "'", '"')
LOG_SELE = LTRIM(STR(SELECT()))
SL_SQL = "insert into sys_log (ID,CreateTime,LogLevel,Operator,Location,Description) values (?log_ID,'"
SL_SQL = SL_SQL+TTOC(DATETIME())+"',"
SL_SQL = SL_SQL+STR(SL_LOGLEVEL, 2)+",'"
IF EMPTY(PUB_USER)
SL_SQL = SL_SQL+"SYS"+" ("+SYS(0)+")','"
ELSE
SL_SQL = SL_SQL+PUB_USER+" ("+SYS(0)+")','"
ENDIF
SL_SQL = SL_SQL+SL_LOCATION+"','"
SL_SQL = SL_SQL+IIF(LEN(SL_DESCRIPTION)>127, LEFT(SL_DESCRIPTION, 127), SL_DESCRIPTION)+"')"
LOG_ID = AUTOCOUNT(7)
IF LOG_ID<0
RETURN
ENDIF
LOG_ID = LOG_ID
SQLEXE_RUN(00000000032, SYS(16), SL_SQL, "sys_log")
SELECT &LOG_SELE
ENDIF
RETURN
ENDPROC
**
