**
FUNCTION SYSPASS
PARAMETER PASS_STR, MOD
MSTR = ' '
I = 1
J = LEN(PASS_STR)
IF MOD
DO WHILE I<=J
ZF = CHR(MOD(ASC(SUBSTR(PASS_STR, I, 1))+J*33, 100))+CHR(INT((ASC(SUBSTR(PASS_STR, I, 1))+J*33)/100))
MSTR = MSTR+ZF
I = I+1
ENDDO
ELSE
DO WHILE I<=J
MCHR = ASC(SUBSTR(PASS_STR, I+1, 1))*100+ASC(SUBSTR(PASS_STR, I, 1))-J/2*33
IF MCHR<0 .OR. MCHR>255
MSTR = ' '
EXIT
ENDIF
ZF = CHR(MCHR)
MSTR = MSTR+ZF
I = I+2
ENDDO
ENDIF
RETURN LTRIM(MSTR)
ENDFUNC
**
