**
PROCEDURE WriteLog
PARAMETER SSTRING
IF  .NOT. DIRECTORY("Log")
MD Log
ENDIF
LSDATETIME = STRTRAN(DTOC(DATE()), "/", "")
LSLOGFILENAME = "Log\"+LSDATETIME+".log"
SOUTPUTSTRING = ""
LSLOGSTR = ""
IF FILE(LSLOGFILENAME)
LSLOGSTR = READSTRFROMFILE(LSLOGFILENAME, SOUTPUTSTRING)
ENDIF
LSLOGSTR = LSLOGSTR+RIGHT(TTOC(DATETIME()), 8)+","+SSTRING+CHR(13)
SAVESTRTOFILE(LSLOGSTR, LSLOGFILENAME)
ENDPROC
**
